# Generated by Django 5.1.4 on 2026-09-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycard',
            name='emergency_token',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
    ]
