# Generated by Django 5.1.4 on 2026-09-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_card', '0002_emergencycard_emergency_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycard',
            name='emergency_token',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
    ]
