# Generated by Django 5.1.4 on 2026-09-17 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('GRANT_ACCESS', 'Grant Access'), ('REVOKE_ACCESS', 'Revoke Access'), ('GRANT_CONSENT', 'Grant Consent'), ('REVOKE_CONSENT', 'Revoke Consent'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=30)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_logs__user_id_c41764_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs__resourc_760a22_idx'), models.Index(fields=['action', '-created_at'], name='audit_logs__action_7c186a_idx')],
            },
        ),
    ]
