# Generated by Django 5.1.4 on 2026-09-14 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('record_type', models.CharField(choices=[('PRESCRIPTION', 'Prescription'), ('LAB_REPORT', 'Lab Report'), ('BLOOD_REPORT', 'Blood Report'), ('XRAY', 'X-Ray'), ('MRI', 'MRI'), ('CT_SCAN', 'CT Scan'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('MEDICAL_HISTORY', 'Medical History'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='medical_records/%Y/%m/')),
                ('record_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
