# Generated by Django 5.1.4 on 2026-09-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('PRESCRIPTION', 'Prescription'), ('LAB_REPORT', 'Lab Report'), ('BLOOD_REPORT', 'Blood Report'), ('XRAY', 'X-Ray'), ('MRI', 'MRI'), ('CT_SCAN', 'CT Scan'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('MEDICAL_HISTORY', 'Medical History'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
