# Generated by Django 5.1.4 on 2026-09-20 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0002_alter_medicalrecord_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the canonical medical record data.', max_length=64)),
                ('hash_algorithm', models.CharField(default='SHA-256', max_length=20)),
                ('proof_type', models.CharField(default='MEDICAL_RECORD', max_length=30)),
                ('block_reference', models.CharField(blank=True, help_text='Optional future blockchain/ledger transaction reference.', max_length=255, null=True)),
                ('previous_hash', models.CharField(blank=True, help_text='Hash of the previous integrity proof for this record.', max_length=64, null=True)),
                ('verification_count', models.PositiveIntegerField(default=0)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integrity_proofs', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_proofs', to='medical_records.medicalrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['medical_record', '-created_at'], name='blockchain__medical_0bec3f_idx'), models.Index(fields=['record_hash'], name='blockchain__record__696900_idx'), models.Index(fields=['is_valid', '-created_at'], name='blockchain__is_vali_0d51fb_idx')],
            },
        ),
    ]
