# Generated by Django 5.1.4 on 2026-09-19 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_securityalert_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfasetting',
            name='backup_codes',
        ),
        migrations.RemoveField(
            model_name='mfasetting',
            name='secret',
        ),
        migrations.AddField(
            model_name='mfasetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mfasetting',
            name='secret_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mfasetting',
            name='method',
            field=models.CharField(choices=[('TOTP', 'Authenticator App')], default='TOTP', max_length=20),
        ),
    ]
